### PR TITLE
DDF-4286 Add thirdparty module for cas-client-core dependency

### PR DESCRIPTION
**Pull request by SmithJosh**
#### Description
There was an issue with our CAS client dependency that caused issues when trying to do CAS auth behind a proxy. This issue was fixed, but there's not been a CAS client release since then and CAS auth needs to work for DDF 2.13.3. This PR creates a custom release of the CAS client which DDF can pull in. It is only intended to be a temporary solution until the next CAS client release is cut.

I went ahead and removed the existing cas-client-core-3.1.10 module because it's not used anymore.

#### Ticket
[DDF-4286](https://codice.atlassian.net/browse/DDF-4286)

#### Reviewers
@brendan-hofmann @vinamartin @alexaabrd @clockard

### CODE REVIEW

**Comment by clockard** [comment]
Rather than just include the snapshot jar cas-client-core-3.5.1-SNAPSHOT.jar I think it would be better to just include the cas-client-core module code and release that.

**Comment by SmithJosh** [comment]
@clockard I changed the module to build the CAS client sources instead of dropping the jar. The changes are split into three commits:
1. Clone cas-client-core 3.5.0
2. Fix the issue that prevented CAS auth behind a proxy
3. Make it a bundle

Can we keep the commits split this time so there's a record of what we changed in the CAS sources?

**Comment by clockard** [comment]
@SmithJosh we can keep the commits

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
Hero build passed

**Comment by brendan-hofmann** [comment]
Verified.

**Pull request merged**
